export const SKILL_DOC_URLS: Readonly<Record<string, string>> = {
  TypeScript: 'https://www.typescriptlang.org/docs/',
  'JavaScript (ES6+)': 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  HTML5: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  CSS3: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  React: 'https://react.dev/learn',
  'React Native (Expo SDK)': 'https://reactnative.dev/docs/getting-started',
  'Next.js (SSR/SSG/ISR)': 'https://nextjs.org/docs',
  'Node.js': 'https://nodejs.org/docs/latest/api/',
  'Apache Cordova': 'https://cordova.apache.org/docs/en/latest/',
  'Redux Toolkit': 'https://redux-toolkit.js.org/',
  MobX: 'https://mobx.js.org/README.html',
  Zustand: 'https://zustand.docs.pmnd.rs/getting-started/introduction',
  'TanStack React Query': 'https://tanstack.com/query/latest/docs/framework/react/overview',
  'Apollo GraphQL': 'https://www.apollographql.com/docs/',
  REST: 'https://developer.mozilla.org/en-US/docs/Glossary/REST',
  WebSockets: 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API',
  'React Hook Form': 'https://react-hook-form.com/get-started',
  Formik: 'https://formik.org/docs/overview',
  Zod: 'https://zod.dev/',
  'Material UI': 'https://mui.com/material-ui/getting-started/',
  'Fluent UI': 'https://react.fluentui.dev/',
  'Tailwind CSS': 'https://tailwindcss.com/docs',
  SCSS: 'https://sass-lang.com/documentation/',
  'CSS Modules': 'https://github.com/css-modules/css-modules',
  'Styled-Components': 'https://styled-components.com/docs',
  Jest: 'https://jestjs.io/docs/getting-started',
  'React Testing Library': 'https://testing-library.com/docs/react-testing-library/intro/',
  Playwright: 'https://playwright.dev/docs/intro',
  Vitest: 'https://vitest.dev/guide/',
  Vite: 'https://vite.dev/guide/',
  Webpack: 'https://webpack.js.org/concepts/',
  Babel: 'https://babeljs.io/docs/',
  ESLint: 'https://eslint.org/docs/latest/',
  Prettier: 'https://prettier.io/docs/',
  Storybook: 'https://storybook.js.org/docs',
  'Monorepo (Turborepo, Nx)': 'https://turbo.build/repo/docs',
  Docker: 'https://docs.docker.com/',
  Firebase: 'https://firebase.google.com/docs',
  Postman: 'https://learning.postman.com/docs/introduction/overview/',
  Swagger: 'https://swagger.io/docs/',
  'CI/CD (GitHub Actions, CircleCI, Bitbucket)': 'https://docs.github.com/en/actions',
  GCP: 'https://cloud.google.com/docs',
  Git: 'https://git-scm.com/doc',
  WordPress: 'https://developer.wordpress.org/',
  Contentful: 'https://www.contentful.com/developers/docs/',
  'Claude Code': 'https://docs.anthropic.com/en/docs/claude-code/overview',
  'GitHub Copilot': 'https://docs.github.com/en/copilot',
  Codex: 'https://developers.openai.com/codex',
  'Component-Driven Development': 'https://www.componentdriven.org/',
  'Feature-Sliced Design': 'https://feature-sliced.github.io/documentation/',
}
